name: "Yocto Build"
description: "Builds a project using Yocto"
inputs:
  init-command:
    description: "Command to initialize the repository"
    default: "cd poky && source oe-init-build-env"
  bitbake-command:
    description: "Command to bitbake"
    default: "bitbake"
    required: true
  deploy-dir:
    description: "Yocto deploy directory"
    default: "poky/build/tmp/"
  build-dir:
    description: "Yocto build directory"
    default: "poky/build"
  tmp-dir:
    description: "Yocto tmp directory"
    default: "poky/build/tmp/deploy/images"
  sstate-cache-dir:
    description: "Yocto sstate-cache directory"
    default: "poky/build/sstate-cache"
  image-name:
    description: "Image to build"
    default: "core-image-sato"
    required: true
  pre-command:
    description: "Command to run before baking"
    default: ""
  wks_file:
    description: "Openembedded kickstart file"
    default: null

runs:
  using: "composite"
  steps:
    - name: Setup Yocto environment
      shell: bash
      run: |
        sudo apt install -y gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev python3-subunit mesa-common-dev zstd liblz4-tool file locales libacl1
        sudo locale-gen en_US.UTF-8
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup and build yocto image
      shell: bash
      env:
        YOCTO_INIT_COMMAND: ${{ inputs.init-command }}
        SSTATE_CACHE_DIR: ${{ inputs.sstate-cache-dir }}
        PRE_COMMAND: ${{ inputs.pre-command }}
        BITBAKE_COMMAND: ${{ inputs.bitbake-command }}
        IMAGE_NAME: ${{ inputs.image-name }}
      run: |
        echo "Running `${YOCTO_INIT_COMMAND}`"
        ${YOCTO_INIT_COMMAND}
        echo "Fetching sstate-cache (gh artifactory). Currently unsupported"
        echo "sstate-cache directory: ${SSTATE_CACHE_DIR}"
        echo "Running pre-command: ${PRE_COMMAND}"
        ${PRE_COMMAND}
        which ${BITBAKE_COMMAND}
        ${BITBAKE_COMMAND} --help
        echo "Running bake command: ${BITBAKE_COMMAND} ${IMAGE_NAME}"
        ${BITBAKE_COMMAND} ${IMAGE_NAME} && echo "Done"
    - name: Saving sstate-cache artifact
      uses: actions/upload-artifact@v4
      with:
        name: sstate-cache
        path: ${{ inputs.sstate-cache-dir }}
    - name: Saving deploy artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy
        path: ${{ inputs.deploy-dir }}
